/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminDemoRouteImport } from './routes/super-admin-demo'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminWhitelabelRouteImport } from './routes/super-admin.whitelabel'
import { Route as SuperAdminSupportRouteImport } from './routes/super-admin.support'
import { Route as SuperAdminSuccessRouteImport } from './routes/super-admin.success'
import { Route as SuperAdminPlansRouteImport } from './routes/super-admin.plans'
import { Route as SuperAdminPaymentsRouteImport } from './routes/super-admin.payments'
import { Route as SuperAdminModulesRouteImport } from './routes/super-admin.modules'
import { Route as SuperAdminComplianceRegistryRouteImport } from './routes/super-admin.compliance-registry'
import { Route as SuperAdminComplianceKnowledgeRouteImport } from './routes/super-admin.compliance-knowledge'
import { Route as SuperAdminCompaniesRouteImport } from './routes/super-admin.companies'
import { Route as SuperAdminBillingRouteImport } from './routes/super-admin.billing'
import { Route as SuperAdminAuditRouteImport } from './routes/super-admin.audit'
import { Route as SuperAdminAiRouteImport } from './routes/super-admin.ai'

const SuperAdminDemoRoute = SuperAdminDemoRouteImport.update({
  id: '/super-admin-demo',
  path: '/super-admin-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminWhitelabelRoute = SuperAdminWhitelabelRouteImport.update({
  id: '/whitelabel',
  path: '/whitelabel',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSupportRoute = SuperAdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSuccessRoute = SuperAdminSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPlansRoute = SuperAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPaymentsRoute = SuperAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminModulesRoute = SuperAdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminComplianceRegistryRoute =
  SuperAdminComplianceRegistryRouteImport.update({
    id: '/compliance-registry',
    path: '/compliance-registry',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminComplianceKnowledgeRoute =
  SuperAdminComplianceKnowledgeRouteImport.update({
    id: '/compliance-knowledge',
    path: '/compliance-knowledge',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminCompaniesRoute = SuperAdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminBillingRoute = SuperAdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAuditRoute = SuperAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAiRoute = SuperAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => SuperAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/super-admin-demo': typeof SuperAdminDemoRoute
  '/super-admin/ai': typeof SuperAdminAiRoute
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/billing': typeof SuperAdminBillingRoute
  '/super-admin/companies': typeof SuperAdminCompaniesRoute
  '/super-admin/compliance-knowledge': typeof SuperAdminComplianceKnowledgeRoute
  '/super-admin/compliance-registry': typeof SuperAdminComplianceRegistryRoute
  '/super-admin/modules': typeof SuperAdminModulesRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/plans': typeof SuperAdminPlansRoute
  '/super-admin/success': typeof SuperAdminSuccessRoute
  '/super-admin/support': typeof SuperAdminSupportRoute
  '/super-admin/whitelabel': typeof SuperAdminWhitelabelRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/super-admin-demo': typeof SuperAdminDemoRoute
  '/super-admin/ai': typeof SuperAdminAiRoute
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/billing': typeof SuperAdminBillingRoute
  '/super-admin/companies': typeof SuperAdminCompaniesRoute
  '/super-admin/compliance-knowledge': typeof SuperAdminComplianceKnowledgeRoute
  '/super-admin/compliance-registry': typeof SuperAdminComplianceRegistryRoute
  '/super-admin/modules': typeof SuperAdminModulesRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/plans': typeof SuperAdminPlansRoute
  '/super-admin/success': typeof SuperAdminSuccessRoute
  '/super-admin/support': typeof SuperAdminSupportRoute
  '/super-admin/whitelabel': typeof SuperAdminWhitelabelRoute
  '/super-admin': typeof SuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/super-admin-demo': typeof SuperAdminDemoRoute
  '/super-admin/ai': typeof SuperAdminAiRoute
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/billing': typeof SuperAdminBillingRoute
  '/super-admin/companies': typeof SuperAdminCompaniesRoute
  '/super-admin/compliance-knowledge': typeof SuperAdminComplianceKnowledgeRoute
  '/super-admin/compliance-registry': typeof SuperAdminComplianceRegistryRoute
  '/super-admin/modules': typeof SuperAdminModulesRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/plans': typeof SuperAdminPlansRoute
  '/super-admin/success': typeof SuperAdminSuccessRoute
  '/super-admin/support': typeof SuperAdminSupportRoute
  '/super-admin/whitelabel': typeof SuperAdminWhitelabelRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/super-admin'
    | '/super-admin-demo'
    | '/super-admin/ai'
    | '/super-admin/audit'
    | '/super-admin/billing'
    | '/super-admin/companies'
    | '/super-admin/compliance-knowledge'
    | '/super-admin/compliance-registry'
    | '/super-admin/modules'
    | '/super-admin/payments'
    | '/super-admin/plans'
    | '/super-admin/success'
    | '/super-admin/support'
    | '/super-admin/whitelabel'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/super-admin-demo'
    | '/super-admin/ai'
    | '/super-admin/audit'
    | '/super-admin/billing'
    | '/super-admin/companies'
    | '/super-admin/compliance-knowledge'
    | '/super-admin/compliance-registry'
    | '/super-admin/modules'
    | '/super-admin/payments'
    | '/super-admin/plans'
    | '/super-admin/success'
    | '/super-admin/support'
    | '/super-admin/whitelabel'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/super-admin'
    | '/super-admin-demo'
    | '/super-admin/ai'
    | '/super-admin/audit'
    | '/super-admin/billing'
    | '/super-admin/companies'
    | '/super-admin/compliance-knowledge'
    | '/super-admin/compliance-registry'
    | '/super-admin/modules'
    | '/super-admin/payments'
    | '/super-admin/plans'
    | '/super-admin/success'
    | '/super-admin/support'
    | '/super-admin/whitelabel'
    | '/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  SuperAdminDemoRoute: typeof SuperAdminDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin-demo': {
      id: '/super-admin-demo'
      path: '/super-admin-demo'
      fullPath: '/super-admin-demo'
      preLoaderRoute: typeof SuperAdminDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/whitelabel': {
      id: '/super-admin/whitelabel'
      path: '/whitelabel'
      fullPath: '/super-admin/whitelabel'
      preLoaderRoute: typeof SuperAdminWhitelabelRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/support': {
      id: '/super-admin/support'
      path: '/support'
      fullPath: '/super-admin/support'
      preLoaderRoute: typeof SuperAdminSupportRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/success': {
      id: '/super-admin/success'
      path: '/success'
      fullPath: '/super-admin/success'
      preLoaderRoute: typeof SuperAdminSuccessRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/plans': {
      id: '/super-admin/plans'
      path: '/plans'
      fullPath: '/super-admin/plans'
      preLoaderRoute: typeof SuperAdminPlansRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/payments': {
      id: '/super-admin/payments'
      path: '/payments'
      fullPath: '/super-admin/payments'
      preLoaderRoute: typeof SuperAdminPaymentsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/modules': {
      id: '/super-admin/modules'
      path: '/modules'
      fullPath: '/super-admin/modules'
      preLoaderRoute: typeof SuperAdminModulesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/compliance-registry': {
      id: '/super-admin/compliance-registry'
      path: '/compliance-registry'
      fullPath: '/super-admin/compliance-registry'
      preLoaderRoute: typeof SuperAdminComplianceRegistryRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/compliance-knowledge': {
      id: '/super-admin/compliance-knowledge'
      path: '/compliance-knowledge'
      fullPath: '/super-admin/compliance-knowledge'
      preLoaderRoute: typeof SuperAdminComplianceKnowledgeRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/companies': {
      id: '/super-admin/companies'
      path: '/companies'
      fullPath: '/super-admin/companies'
      preLoaderRoute: typeof SuperAdminCompaniesRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/billing': {
      id: '/super-admin/billing'
      path: '/billing'
      fullPath: '/super-admin/billing'
      preLoaderRoute: typeof SuperAdminBillingRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/audit': {
      id: '/super-admin/audit'
      path: '/audit'
      fullPath: '/super-admin/audit'
      preLoaderRoute: typeof SuperAdminAuditRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/ai': {
      id: '/super-admin/ai'
      path: '/ai'
      fullPath: '/super-admin/ai'
      preLoaderRoute: typeof SuperAdminAiRouteImport
      parentRoute: typeof SuperAdminRoute
    }
  }
}

interface SuperAdminRouteChildren {
  SuperAdminAiRoute: typeof SuperAdminAiRoute
  SuperAdminAuditRoute: typeof SuperAdminAuditRoute
  SuperAdminBillingRoute: typeof SuperAdminBillingRoute
  SuperAdminCompaniesRoute: typeof SuperAdminCompaniesRoute
  SuperAdminComplianceKnowledgeRoute: typeof SuperAdminComplianceKnowledgeRoute
  SuperAdminComplianceRegistryRoute: typeof SuperAdminComplianceRegistryRoute
  SuperAdminModulesRoute: typeof SuperAdminModulesRoute
  SuperAdminPaymentsRoute: typeof SuperAdminPaymentsRoute
  SuperAdminPlansRoute: typeof SuperAdminPlansRoute
  SuperAdminSuccessRoute: typeof SuperAdminSuccessRoute
  SuperAdminSupportRoute: typeof SuperAdminSupportRoute
  SuperAdminWhitelabelRoute: typeof SuperAdminWhitelabelRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminAiRoute: SuperAdminAiRoute,
  SuperAdminAuditRoute: SuperAdminAuditRoute,
  SuperAdminBillingRoute: SuperAdminBillingRoute,
  SuperAdminCompaniesRoute: SuperAdminCompaniesRoute,
  SuperAdminComplianceKnowledgeRoute: SuperAdminComplianceKnowledgeRoute,
  SuperAdminComplianceRegistryRoute: SuperAdminComplianceRegistryRoute,
  SuperAdminModulesRoute: SuperAdminModulesRoute,
  SuperAdminPaymentsRoute: SuperAdminPaymentsRoute,
  SuperAdminPlansRoute: SuperAdminPlansRoute,
  SuperAdminSuccessRoute: SuperAdminSuccessRoute,
  SuperAdminSupportRoute: SuperAdminSupportRoute,
  SuperAdminWhitelabelRoute: SuperAdminWhitelabelRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  SuperAdminDemoRoute: SuperAdminDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
